llm:
  type: openai
  model: gpt-4o-mini
  temperature: 0.2
  max_tokens: 150
  # verbose: true

stt:
  type: deepgram
  model: nova-3
  language: en

tts:
  type: cartesia
  model: sonic-2
  language: en
